safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "ProcGen"
description: "build dreams, see beauty, learn to think"
baseurl: "/procgen_site" # swap this out when running locally
url: "https://hoqqanen.github.io/procgen_site/" # replace with site's url

author: "George Hoqqanen"
address: ""
email: "george@hoqqanen.com"

exclude:
  - LICENSE
  - README.md

gems:
  - octopress-autoprefixer

sass:
    sass_dir: _sass